version: "3"

services:
  logger-service:
    build:
      context: ./logger-service
      dockerfile: ./Dockerfile
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password

  queue-listener:
    build:
      context: ./queue-listener
      dockerfile: ./Dockerfile
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=jobs sslmode=disable timezone=Europe/Amsterdam connect_timeout=5"

  postgres:
    image: 'postgres:latest'
    restart: always
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobs
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: 'mongo:4.2.16-bionic'
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - './db-data/mongodb/:/data/db'
